# Generated by Django 3.1.5 on 2021-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='production_date',
            field=models.PositiveIntegerField(),
        ),
    ]
