# Generated by Django 3.1.5 on 2021-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210109_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.ManyToManyField(blank=True, to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
